### ISSUE TITLE
Python SQL Raw Query Issue

### ISSUE THREAD

**Issue by ashishsme14** [fernaper/flask_api_generator#12]
We had given a task and for which we written below code, while executing it showing an error. Hence issue in sqlalchemy need help for . Please let us know where we went wrong in coding-

```
from sqlalchemy import create_engine
db_string = "sqlite:///tests.db"
db = create_engine(db_string)

#create
db.execute("CREATE TABLE IF NOT EXISTS players (plyid text, plyname text, runs text)")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10001', 'Ply1', '100')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10002', 'Ply2', '80')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10003', 'Ply3', '65')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10004', 'Ply4', '95')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10005', 'Ply5', '99')")
   

# Read
s=[]
result_set = db.execute("SELECT * FROM players")
for s1 in result_set:
    print(s)

#Update
q=[]
db.execute("UPDATE players SET runs='100' WHERE plyid='10005'")
result_set1 = db.execute("SELECT * FROM players")
for s2 in result_set1:
    print(q)

#Delete
e=[]
db.execute("DELETE FROM players WHERE plyid='10005'")
result_set2 = db.execute("SELECT * FROM players")
for s3 in result_set2:
    print(e)

s=str(s)
q=str(q)
e=str(e)
with open(".hidden.txt",'w') as f:
    f.write(s)

with open(".hidden1.txt",'w') as f:
    f.write(q)

with open(".hidden2.txt",'w') as outfile:
    outfile.write(e)

```

Here our issue is that we need to combine for example` S[] `with S1 so that output will be
`('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '99')`

similar `q[]` with S2 so that output will be
`('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '100')`

Finally` e[] `with S3 so that output will be
`('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95')
`
As we not getting above output hence we getting error while executing. Hence please suggest how we can append both.

**Comment by fernaper** [comment]
Hi, this question does not make sense in this project, however, let me help you.

I'm not pretty sure if understand what you are trying to do.
I suppose that first, you want to read all players from database and store them on `result_set`.

If that is the case you can simply execute:

```python
from sqlalchemy import create_engine
db_string = "sqlite:///tests.db"
db = create_engine(db_string)

# Create
db.execute("CREATE TABLE IF NOT EXISTS players (plyid text, plyname text, runs text)")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10001', 'Ply1', '100')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10002', 'Ply2', '80')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10003', 'Ply3', '65')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10004', 'Ply4', '95')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10005', 'Ply5', '99')")

# Read
result_set = db.execute("SELECT * FROM players")
s = list(result_set)
print(s)
# the result will be: [('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '99')]
```

It is exactly the same for `result_set1` and `result_set2`.

On the other hand, you are using SQL statements to get the results, modify them and delete them. Since **SQLAlchemy** is an **ORM** (Object-relational mapping), you should not do that.
Instead you should create a `Players` class, with the `plyid`, `plyname` and `runs` attributes, and use SQLAlchemy's functionalities to query, modify and delete the data.

Let me know if you have any questions or problems, if not in a couple of days I will close the issue.

Good luck!

**Comment by ashishsme14** [comment]
Thanks for quick response ..here we have constant as

`s[ ]`

So s = list(result_set) will work

**Comment by ashishsme14** [comment]
[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '99')]

[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '100')]

[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95')]

============================= test session starts ==============================

platform linux -- Python 3.5.2, pytest-3.2.1, py-1.9.0, pluggy-0.4.0

rootdir: /projects/challenge, inifile:

collected 3 items

test.py FFF

=================================== FAILURES ===================================

____________________________________ test_s ____________________________________

    def test_s():

>       assert s == "2961f24308da3f873dece8f5bdbee76c"

E       AssertionError: assert 'e0588b34d350...af6e56f2933f9' == '2961f24308da3...ce8f5bdbee76c'

E         - e0588b34d3506585138af6e56f2933f9

E         + 2961f24308da3f873dece8f5bdbee76c

test.py:12: AssertionError

___________________________________ test_s1 ____________________________________

    def test_s1():

>       assert s1 == "7d886c29952aa5e4958116bb637c3eec"

E       AssertionError: assert 'a50642994d22...ffbae90512a84' == '7d886c29952aa...116bb637c3eec'

E         - a50642994d2288294cfffbae90512a84

E         + 7d886c29952aa5e4958116bb637c3eec

test.py:15: AssertionError

___________________________________ test_s2 ____________________________________

    def test_s2():

>       assert s2 == "2c1d559ea642334b391146cbfe613b24"

E       AssertionError: assert '6c8c42294e28...a115f797fca9b' == '2c1d559ea6423...146cbfe613b24'

E         - 6c8c42294e28dbb53c4a115f797fca9b

E         + 2c1d559ea642334b391146cbfe613b24

test.py:18: AssertionError

=========================== 3 failed in 0.03 seconds ===========================

**Comment by ashishsme14** [comment]
from hashlib import md5
f = open(".hidden.txt", "r")
g= open(".hidden1.txt","r")
p=open(".hidden2.txt","r")
s=f.readline()
s1=g.readline()
s2=p.readline()
s=md5(str.encode(s)).hexdigest()
s1=md5(str.encode(s1)).hexdigest()
s2=md5(str.encode(s2)).hexdigest()
def test_s():
    assert s == "2961f24308da3f873dece8f5bdbee76c"

def test_s1():
    assert s1 == "7d886c29952aa5e4958116bb637c3eec"

def test_s2():
    assert s2 == "2c1d559ea642334b391146cbfe613b24"

**Comment by ashishsme14** [comment]
![image](https://user-images.githubusercontent.com/61864865/100544619-19cb8080-327d-11eb-972e-9f130002e83b.png)
![image](https://user-images.githubusercontent.com/61864865/100544647-3e275d00-327d-11eb-9331-52168bd8c2ee.png)
![image](https://user-images.githubusercontent.com/61864865/100544669-55fee100-327d-11eb-84d5-3538538877e9.png)

**Comment by ashishsme14** [comment]
```
from sqlalchemy import create_engine
db_string = "sqlite:///tests.db"
db = create_engine(db_string)

#create
db.execute("CREATE TABLE IF NOT EXISTS players (plyid text, plyname text, runs text)")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10001', 'Ply1', '100')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10002', 'Ply2', '80')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10003', 'Ply3', '65')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10004', 'Ply4', '95')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10005', 'Ply5', '99')")


# Read
s=[]
result_set = db.execute("SELECT * FROM players")
s = list(result_set)
print(s)

#Update
q=[]
db.execute("UPDATE players SET runs='100' WHERE plyid='10005'")
result_set1 = db.execute("SELECT * FROM players")
q= list(result_set1)
print(q)

#Delete

e = []
db.execute("DELETE FROM players WHERE plyid='10005'")
result_set2 = db.execute("SELECT * FROM players")
e = list(result_set2)
print(e)

s=str(s)
q=str(q)
e=str(e)
with open(".hidden.txt",'w') as f:
    f.write(s)

with open(".hidden1.txt",'w') as f:
    f.write(q)

with open(".hidden2.txt",'w') as outfile:
    outfile.write(e)

```

**Comment by ashishsme14** [comment]
[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '99')]

[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95'), ('10005', 'Ply5', '100')]

[('10001', 'Ply1', '100'), ('10002', 'Ply2', '80'), ('10003', 'Ply3', '65'), ('10004', 'Ply4', '95')]

============================= test session starts ==============================

platform linux -- Python 3.5.2, pytest-3.2.1, py-1.9.0, pluggy-0.4.0

rootdir: /projects/challenge, inifile:

collected 3 items

test.py FFF

=================================== FAILURES ===================================

____________________________________ test_s ____________________________________

    def test_s():

>       assert s == "2961f24308da3f873dece8f5bdbee76c"

E       AssertionError: assert 'f16b4d66ac76...50b404dafe297' == '2961f24308da3...ce8f5bdbee76c'

E         - f16b4d66ac76fa9718c50b404dafe297

E         + 2961f24308da3f873dece8f5bdbee76c

test.py:12: AssertionError

___________________________________ test_s1 ____________________________________

    def test_s1():

>       assert s1 == "7d886c29952aa5e4958116bb637c3eec"

E       AssertionError: assert '1e71f6454661...8178b56990513' == '7d886c29952aa...116bb637c3eec'

E         - 1e71f64546615342bd18178b56990513

E         + 7d886c29952aa5e4958116bb637c3eec

test.py:15: AssertionError

___________________________________ test_s2 ____________________________________

    def test_s2():

>       assert s2 == "2c1d559ea642334b391146cbfe613b24"

E       AssertionError: assert 'ca7a2147e926...2773a7c816739' == '2c1d559ea6423...146cbfe613b24'

E         - ca7a2147e9267ce80682773a7c816739

E         + 2c1d559ea642334b391146cbfe613b24

test.py:18: AssertionError

=========================== 3 failed in 0.04 seconds ===========================

**Comment by ashishsme14** [comment]
Hope now our expectation is been cleared?

**Comment by fernaper** [comment]
Yes, now I understand the problem perfectly.
The problem here is that your hidden files have the text `PlyX` with the letter **P** in capital letters, but it should be in lowercase.

Just change the part of your code where you create an insert data into the table with next lines:

```python
#create
db.execute("CREATE TABLE IF NOT EXISTS players (plyid text, plyname text, runs text)")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10001', 'ply1', '100')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10002', 'ply2', '80')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10003', 'ply3', '65')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10004', 'ply4', '95')")
db.execute("INSERT INTO players (plyid, plyname, runs) VALUES ('10005', 'ply5', '99')")
```

I hope it helps you.

Anyway, I'm not going to continue solving these problems here, since they have nothing to do with this repository.
On the other hand, it seems that these are exercises that you should try to solve yourself.

Good luck!
